server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs for DNS servers
  - job_name: docker-dns-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["rind-dns-primary", "rind-dns-secondary"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'service'
        regex: 'rind-dns-(.*)'
        replacement: 'dns-server-${1}'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
        regex: '(.{12})'
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            target: target
            filename: filename
            line_number: line_number
            threadId: threadId
      - labels:
          level:
          target:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message