apiVersion: v1
kind: Service
metadata:
  name: rind-dns
  namespace: rind-system
spec:
  type: NodePort
  ports:
    - name: dns
      port: 53
      targetPort: 12312
      protocol: UDP
      nodePort: 30053
