apiVersion: v1
kind: Service
metadata:
  name: rind-dns
  namespace: rind-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
spec:
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
      targetPort: 12312
      protocol: UDP
