global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'dns-server-monitor'

rule_files:
  - "record-management-alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DNS servers with Docker service discovery
  - job_name: 'dns-servers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9090
        filters:
          - name: label
            values: ["com.docker.compose.service=dns-server"]
    relabel_configs:
      # Use container name as instance label
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      # Use service label for job identification
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      # Add server ID from environment variable
      - source_labels: [__meta_docker_container_label_server_id]
        target_label: server_id
      # Keep only containers with prometheus scrape label
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        action: keep
        regex: true
      # Use custom metrics path if specified
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        target_label: __metrics_path__
        regex: (.+)
      # Use custom port if specified
      - source_labels: [__address__, __meta_docker_container_label_prometheus_io_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2

  # Static configuration for DNS servers
  - job_name: 'dns-servers-static'
    static_configs:
      - targets: 
          - 'dns-server-primary:9090'
          - 'dns-server-secondary:9090'
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance
        replacement: '${1}'



  # System metrics from Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: 'system-metrics'
      - target_label: instance
        replacement: 'rind-host'

  # Container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: 'container-metrics'

  # HAProxy load balancer metrics
  - job_name: 'haproxy'
    static_configs:
      - targets: ['load-balancer:8404']
    scrape_interval: 15s
    metrics_path: /stats/prometheus
    relabel_configs:
      - target_label: service
        replacement: 'load-balancer'

  # DNS Canary monitoring
  - job_name: 'dns-canary'
    static_configs:
      - targets: ['host.docker.internal:8090']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: 'dns-canary'

  # RIND System Metrics Exporter
  - job_name: 'rind-system-metrics'
    static_configs:
      - targets: ['system-metrics-exporter:8091']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - target_label: service
        replacement: 'rind-system-metrics'
      - target_label: instance
        replacement: 'rind-system'