apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rind.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rind.labels" . | nindent 4 }}
data:
  RIND_MODE: {{ .Values.config.mode | quote }}
  RIND_NAMESPACE: {{ .Release.Namespace | quote }}
  DNS_BIND_ADDR: {{ .Values.config.dnsBind | quote }}
  API_BIND_ADDR: {{ .Values.config.apiBind | quote }}
  METRICS_PORT: {{ .Values.config.metricsPort | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  DISABLE_FILE_LOGGING: {{ .Values.config.disableFileLogging | quote }}
  RIND_LMDB_PATH: {{ .Values.config.lmdbPath | quote }}
  RIND_RESYNC_INTERVAL_SECS: {{ .Values.config.resyncIntervalSecs | quote }}
