apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rind.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rind.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rind.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.config.metricsPort | quote }}
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rind
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 12312
              protocol: UDP
              name: dns
            - containerPort: 8080
              protocol: TCP
              name: api
            - containerPort: 9090
              protocol: TCP
              name: metrics
          envFrom:
            - configMapRef:
                name: {{ include "rind.fullname" . }}-config
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          emptyDir: {}
