apiVersion: v1
kind: ConfigMap
metadata:
  name: rind-config
  namespace: rind-system
  labels:
    app.kubernetes.io/name: rind
data:
  RIND_MODE: "kubernetes"
  RIND_NAMESPACE: "rind-system"
  DNS_BIND_ADDR: "0.0.0.0:12312"
  API_BIND_ADDR: "0.0.0.0:8080"
  METRICS_PORT: "9090"
  LOG_FORMAT: "json"
  DISABLE_FILE_LOGGING: "true"
  RIND_LMDB_PATH: "/data/lmdb"
  RIND_RESYNC_INTERVAL_SECS: "300"
