apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rind-system

resources:
  - namespace.yaml
  - crd-dnsrecord.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service-dns.yaml
  - service-api.yaml
  - canary.yaml

configMapGenerator:
  - name: rind-canary-script
    files:
      - dns-canary.py

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
