apiVersion: v1
kind: Service
metadata:
  name: rind-dns
  namespace: rind-system
  labels:
    app.kubernetes.io/name: rind
    app.kubernetes.io/component: dns
spec:
  selector:
    app.kubernetes.io/name: rind
  ports:
    - name: dns
      port: 53
      targetPort: 12312
      protocol: UDP
